"""
dto.py - *Data Transfer Objects* for the Library Management System.

DTOs separate the data flowing IN (from the user / GUI) from the data
flowing OUT (from the database to the GUI).  They serve three purposes:

  1. Validation  – ensure required fields are present before hitting the DB.
  2. Decoupling  – the GUI never touches raw SQL rows; it works with typed objects.
  3. Clarity     – each operation advertises exactly which fields it needs.

Naming convention
─────────────────
  CreateXxxDTO   → fields the caller must supply to INSERT a new row.
  UpdateXxxDTO   → fields the caller may change on an existing row (all optional).
  XxxResponseDTO → fields returned to the caller after a read / write.
"""

from dataclasses import dataclass, field, asdict
from typing import Optional, List
from datetime import date


# ══════════════════════════════════════════════════════════════════════
#  CATEGORY DTOs
# ══════════════════════════════════════════════════════════════════════

@dataclass
class CreateCategoryDTO:
    """
    Fields required to create a new category.
    Only the name is needed; the id is auto-generated by SQLite.
    """
    name: str


@dataclass
class CategoryResponseDTO:
    """Returned when reading a category from the database."""
    id: int
    name: str


# ══════════════════════════════════════════════════════════════════════
#  BOOK DTOs
# ══════════════════════════════════════════════════════════════════════

@dataclass
class CreateBookDTO:
    """
    Fields required to insert a new book.
    - id is auto-generated (AUTOINCREMENT).
    - category_id must reference an existing category.
    - stock defaults to 1 if not supplied.
    """
    title: str
    author: str
    isbn: str
    category_id: int
    stock: int = 1


@dataclass
class UpdateBookDTO:
    """
    Fields that may be changed on an existing book.
    Every field is Optional — only the ones provided will be updated.
    The id and isbn are immutable (not included here).
    """
    title: Optional[str] = None
    author: Optional[str] = None
    category_id: Optional[int] = None
    stock: Optional[int] = None


@dataclass
class BookResponseDTO:
    """Returned when reading a book, includes the resolved category name."""
    id: int
    title: str
    author: str
    isbn: str
    category_id: int
    category_name: str
    stock: int


# ══════════════════════════════════════════════════════════════════════
#  MEMBER DTOs
# ══════════════════════════════════════════════════════════════════════

@dataclass(frozen=True)
class CreateMemberDTO:
    """
    Fields required to register a new member.

    - id              → auto-generated (AUTOINCREMENT).
    - registration_no → auto-generated by the system (e.g. "MEM-006").
                        The caller does NOT supply this; the service layer
                        computes it from the current max id.
    - active          → defaults to 1 (True) on creation.
    - registered_on   → set automatically to today's date.
    """
    full_name: str
    address: Optional[str] = None
    phone: Optional[str] = None
    email: Optional[str] = None
    age: Optional[int] = None
    gender: Optional[str] = None        # "Male" / "Female"
    profession: Optional[str] = None


@dataclass
class UpdateMemberDTO:
    """
    Fields that may be changed on an existing member profile.
    All optional — only provided fields are written to the DB.

    Fields NOT here (and therefore immutable):
      id, registration_no, registered_on, active
    Active status is changed via dedicated renew / deactivate operations,
    not through a generic update.
    """
    full_name: Optional[str] = None
    address: Optional[str] = None
    phone: Optional[str] = None
    email: Optional[str] = None
    age: Optional[int] = None
    gender: Optional[str] = None
    profession: Optional[str] = None


@dataclass
class MemberResponseDTO:
    """Full member profile returned from a read operation."""
    id: int
    full_name: str
    address: Optional[str]
    phone: str
    email: Optional[str]
    age: Optional[int]
    gender: Optional[str]
    profession: Optional[str]
    registration_no: str
    active: bool
    registered_on: str
    renewed_on: Optional[str]


# ══════════════════════════════════════════════════════════════════════
#  LOAN DTOs
# ══════════════════════════════════════════════════════════════════════

@dataclass
class CreateLoanDTO:
    """
    Fields required to borrow a book.
    - id          → auto-generated.
    - loan_date   → set automatically to today.
    - return_date → NULL until the book is returned.
    - rating      → NULL until the member rates the book on return.
    """
    member_id: int
    book_id: int


@dataclass
class ReturnLoanDTO:
    """
    Fields required to return a borrowed book.
    - loan_id identifies which loan is being closed.
    - rating is optional (1-5); the member may skip it.
    """
    loan_id: int
    rating: Optional[int] = None    # 1-5 or None


@dataclass
class LoanResponseDTO:
    """Returned when reading a loan record (active or historical)."""
    id: int
    member_id: int
    book_id: int
    loan_date: str
    return_date: Optional[str]
    rating: Optional[int]
    # Joined fields for display convenience
    book_title: Optional[str] = None
    book_author: Optional[str] = None
    member_name: Optional[str] = None
    category_name: Optional[str] = None


# ══════════════════════════════════════════════════════════════════════
#  STATISTICS DTOs  (read-only, no Create/Update needed)
# ══════════════════════════════════════════════════════════════════════

@dataclass
class DateRangeDTO:
    """Reusable date-range filter used by several statistics queries."""
    date_from: str      # "YYYY-MM-DD"
    date_to: str        # "YYYY-MM-DD"


@dataclass
class CategoryStatDTO:
    """One row in a category-distribution result."""
    category: str
    total: int


@dataclass
class AuthorStatDTO:
    """One row in a loans-per-author result."""
    author: str
    total: int


@dataclass
class AgeStatDTO:
    """One row in a loans-per-age-group result."""
    age: int
    total: int


@dataclass
class GenderStatDTO:
    """One row in a loans-per-gender result."""
    gender: str
    total: int


@dataclass
class RecommendationDTO:
    """A single book recommendation with its computed score."""
    book: BookResponseDTO
    score: float


# ══════════════════════════════════════════════════════════════════════
#  HELPER: convert a raw dict (sqlite3.Row) → typed DTO
# ══════════════════════════════════════════════════════════════════════

def to_member_response(row: dict) -> MemberResponseDTO:
    """Map a database row dict to a MemberResponseDTO."""
    return MemberResponseDTO(
        id=row["id"],
        full_name=row["full_name"],
        address=row.get("address"),
        phone=row.get("phone"),
        email=row.get("email"),
        age=row.get("age"),
        gender=row.get("gender"),
        profession=row.get("profession"),
        registration_no=row["registration_no"],
        active=bool(row["active"]),
        registered_on=row["registered_on"],
        renewed_on=row.get("renewed_on"),
    )


def to_book_response(row: dict) -> BookResponseDTO:
    """Map a database row dict to a BookResponseDTO."""
    return BookResponseDTO(
        id=row["id"],
        title=row["title"],
        author=row["author"],
        isbn=row["isbn"],
        category_id=row["category_id"],
        category_name=row["category_name"],
        stock=row["stock"],
    )


def to_loan_response(row: dict) -> LoanResponseDTO:
    """Map a database row dict to a LoanResponseDTO."""
    return LoanResponseDTO(
        id=row["id"],
        member_id=row["member_id"],
        book_id=row["book_id"],
        loan_date=row["loan_date"],
        return_date=row.get("return_date"),
        rating=row.get("rating"),
        book_title=row.get("book_title"),
        book_author=row.get("book_author"),
        member_name=row.get("member_name"),
        category_name=row.get("category_name"),
    )
